name = "<%= wranglerWorkerName %>"
main = "src/index.ts"
compatibility_date = "2024-01-08"
workers_dev = true

routes = [
	{ pattern = "<%= domainName %>", custom_domain = true },
	{ pattern = "www.<%= domainName %>", custom_domain = true }
]
